eureka:
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8060

#management:
#  security:
#    enabled: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: app-service
          uri: lb://home
          predicates:
            - Path=/home
#          filters:
#            - StripPrefix=1
#  cloud:
#    gateway:
#      routes:
#        - id: app-service
#          uri: lb://app-service
#          predicates:
#            - Path=/**
#          filters:
#            - StripPrefix=1



#zuul:
#  ignoredServices: '*'
#  routes:
#    app-service:
#      path: /svc/**
#      sensitiveHeaders: