# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# cannot extract pack cache, as it's using a named volume

variables:
  ArtifactFeed: 6ebc2d9e-a94e-416e-b463-fea4fdb4ffb8

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      ls -al
  - script: |
      mvn clean package -DskipTests
  - script: |
      ls -al
  - script: |
      docker login -u normanch -p "${pswd}"
    env:
      pswd: $(dockerPassword)
  - script: |
      docker build -t normanch/app-service -f /app-service/Dockerfile .
  - script: |
      docker build -t normanch/config -f /config/Dockerfile .
  - script: |
      docker build -t normanch/gateway -f /gateway/Dockerfile .
  - script: |
      docker build -t normanch/registry -f /registry/Dockerfile .
  - script: |
      docker push normanch/app-service:latest
      docker push normanch/config:latest
      docker push normanch/gateway:latest
      docker push normanch/registry:latest
  - script: |
      docker images
