version: '1'
services:
  registry:
    image: Spring-Azure-DevOps/registry
    ports:
      - "8761:8761"
  config:
    image: Spring-Azure-DevOps/config
    ports:
      - "8888:8888"
  gateway:
    image: Spring-Azure-DevOps/gateway
    ports:
      - "8060:8060"
  app-service:
    image: Spring-Azure-DevOps/app-service