version: '2'
services:
  registry:
    image: normanch/registry
    ports:
      - "8761:8761"
  config:
    image: normanch/config
    ports:
      - "8888:8888"
  gateway:
    image: normanch/gateway
    ports:
      - "8060:8060"
  app-service:
    image: normanch/app-service
    ports:
      - "8070:8070"