#server:
#  port: 8902
#spring:
#  application:
#    name: client
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8901/eureka/
